version: '3'
services:
  db:
    image: postgres:12
    restart: always
    read_only: true
    tmpfs:
      - /tmp
      - /var/run
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: substances
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ChangeThisPasswordN0w!
  substances:
    image: gsrs3:latest
    restart: always
    read_only: true
    tmpfs:
      - /tmp:exec,mode=1777
      - /usr/local/tomcat/work/Catalina/localhost:exec,mode=1777
    volumes:
      - conf:/home/srs/conf:ro
      - exports:/home/srs/exports
      - substances_ix:/home/srs/substances.ix
      - logs:/home/srs/logs
    environment:
      CATALINA_OPTS:
        -Xms4g
        -Xmx4g
        -Dgateway.allow.pattern="\d+\.\d+\.\d+\.\d+"
        -Ddeploy.ignore.pattern="(adverse-events|applications|clinical-trials|frontend|impurities|invitro-pharmacology|products|ssg4m|ROOT)"
      APPLICATION_HOST: http://localhost
      DB_URL_SUBSTANCES: jdbc:postgresql://db:5432/substances
      DB_USERNAME: postgres
      DB_PASSWORD: ChangeThisPasswordN0w!
      DB_DDL_AUTO: update
      DB_DIALECT: gsrs.repository.sql.dialect.GSRSPostgreSQLDialectCustom
    depends_on:
      - db
  frontend:
    image: gsrs3:latest
    restart: always
    read_only: true
    tmpfs:
      - /home/srs/logs
      - /tmp
      - /usr/local/tomcat/work/Catalina/localhost:exec,mode=1777
    volumes:
      - conf:/home/srs/conf:ro
    environment:
      JAVA_OPTS:
        -Xms512m
        -Xmx512m
        -Dgateway.allow.pattern="\d+\.\d+\.\d+\.\d+"
        -Ddeploy.ignore.pattern="(adverse-events|applications|clinical-trials|impurities|invitro-pharmacology|products|ssg4m|substances|ROOT)"
      APPLICATION_HOST: http://localhost
  gateway:
    image: gsrs3:latest
    restart: always
    read_only: true
    tmpfs:
      - /home/srs/logs
      - /tmp
      - /usr/local/tomcat/work/Catalina/localhost:exec,mode=1777
    volumes:
      - conf:/home/srs/conf:ro
    environment:
      JAVA_OPTS:
        -Xms512m
        -Xmx512m
        -Ddeploy.ignore.pattern="(adverse-events|applications|clinical-trials|frontend|impurities|invitro-pharmacology|products|ssg4m|substances)"
      APPLICATION_HOST: http://localhost
      MS_URL_FRONTEND: http://frontend:8080/frontend
      API_URL: http://substances:8080/
    ports:
      - 80:8080
volumes:
  conf:
  db:
  exports:
  substances_ix:
  logs:
